#!/usr/bin/env python3
"""
Generate src/icons_embed.h: the killfeed weapon/death icons, base64-encoded, plus the
CoD2 weapon-configstring -> icon-name mapping, so the --overview HTML is one
self-contained file with game-style icons.

Only the SMALL icons (<= 256px wide) are embedded — the 512/1024px "_c" weapon textures
are far too large for an inline killfeed. Weapons with no icon fall back to text in the
HTML (handled C-side).

Run from the tool root:  python3 scripts/gen_icons_header.py
"""
import os, struct, base64, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS = os.path.join(ROOT, "assets", "icons")
OUT   = os.path.join(ROOT, "src", "icons_embed.h")

# CoD2 weapon configstring name (CS_WEAPONS, minus the trailing _mp) -> icon basename
# in assets/icons. Stance/bipod variants collapse to one icon. Anything not listed (or
# listed as None) renders as text in the killfeed. Verified against the stock weapon
# defs (gfx/icons/hud@<killIcon>) in Refrences/stockrawfiles/iw_13/weapons/mp.
WEAPON_ICON = {
    "bar":                 "weapon_bar",
    "bren":                "weapon_bren",
    "enfield":             "weapon_enfield",
    "enfield_scope":       "weapon_enfieldscoped",
    "g43":                 "weapon_g43",
    "greasegun":           "weapon_greasegun",
    "kar98k":              "weapon_kar98",
    "kar98k_sniper":       "weapon_kar98scoped",
    "m1carbine":           "weapon_m1carbine",
    "m1garand":            "weapon_m1garand",
    "mosin_nagant":        "weapon_nagant",
    "mosin_nagant_sniper": "weapon_nagantscoped",
    "mp40":                "weapon_mp40",
    "mp44":                "weapon_mp44",
    "pps42":               "weapon_pps42",
    "ppsh":                "weapon_ppsh",
    "shotgun":             "weapon_shotgun",
    "springfield":         "weapon_springfield",
    "sten":                "weapon_sten",
    "svt40":               "weapon_svt40",
    "thompson":            "weapon_thompson",
    # No icon converted yet -> text fallback: fg42, 30cal, mg42, colt, luger, tt30,
    # webley, panzerfaust, panzerschreck, grenades, binoculars.
}

# Means-of-death (the MOD names the tool prints) -> death icon basename.
DEATH_ICON = {
    "headshot": "death_headshot",
    "melee":    "death_melee",
    "falling":  "death_falling",
    "crush":    "death_crush",
    "suicide":  "death_suicide",
}

def png_width(path):
    with open(path, "rb") as f:
        b = f.read(24)
    return struct.unpack(">I", b[16:20])[0]

def c_ident(name):
    return "ICON_" + name.upper().replace("-", "_")

def main():
    if not os.path.isdir(ICONS):
        sys.exit(f"icons dir not found: {ICONS}")

    # collect the icons actually referenced by either map, small ones only
    wanted = set(WEAPON_ICON.values()) | set(DEATH_ICON.values())
    embedded = {}
    skipped_big = []
    for name in sorted(wanted):
        p = os.path.join(ICONS, name + ".png")
        if not os.path.exists(p):
            sys.exit(f"referenced icon missing: {p}")
        if png_width(p) > 256:
            skipped_big.append(name)
            continue
        embedded[name] = base64.b64encode(open(p, "rb").read()).decode("ascii")
    if skipped_big:
        sys.exit("these mapped icons are >256px (shrink or remap): " + ", ".join(skipped_big))

    lines = []
    lines.append("// AUTO-GENERATED by scripts/gen_icons_header.py — do not edit by hand.")
    lines.append("// Killfeed weapon/death icons (base64 PNG) + CoD2 weapon->icon mapping.")
    lines.append("#ifndef ICONS_EMBED_H")
    lines.append("#define ICONS_EMBED_H")
    lines.append("")
    lines.append("typedef struct { const char *name; const char *b64; } embeddedIcon_t;")
    lines.append("")
    lines.append("static const embeddedIcon_t g_embeddedIcons[] = {")
    for name in sorted(embedded):
        # chunk the base64 so no single C string line is absurd
        b = embedded[name]
        chunks = [b[i:i+120] for i in range(0, len(b), 120)]
        lines.append(f'\t{{ "{name}",')
        for c in chunks:
            lines.append(f'\t\t"{c}"')
        lines.append("\t},")
    lines.append("};")
    lines.append(f"static const int g_numEmbeddedIcons = {len(embedded)};")
    lines.append("")
    lines.append("typedef struct { const char *key; const char *icon; } iconMap_t;")
    lines.append("")
    lines.append("// weapon configstring name (without trailing _mp, stance-collapsed) -> icon name")
    lines.append("static const iconMap_t g_weaponIcons[] = {")
    for k in sorted(WEAPON_ICON):
        lines.append(f'\t{{ "{k}", "{WEAPON_ICON[k]}" }},')
    lines.append("};")
    lines.append(f"static const int g_numWeaponIcons = {len(WEAPON_ICON)};")
    lines.append("")
    lines.append("// means-of-death name -> death icon")
    lines.append("static const iconMap_t g_deathIcons[] = {")
    for k in sorted(DEATH_ICON):
        lines.append(f'\t{{ "{k}", "{DEATH_ICON[k]}" }},')
    lines.append("};")
    lines.append(f"static const int g_numDeathIcons = {len(DEATH_ICON)};")
    lines.append("")
    lines.append("#endif // ICONS_EMBED_H")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))

    total = sum(len(v) for v in embedded.values())
    print(f"wrote {OUT}")
    print(f"  {len(embedded)} icons embedded ({total//1024}KB base64), "
          f"{len(WEAPON_ICON)} weapon mappings, {len(DEATH_ICON)} death mappings")

if __name__ == "__main__":
    main()
